package main

// docsgen computes step-by-step numerical examples for the layers of the library.
// Every fixture is computed twice: manually with plain loops and via the actual layer
// implementation (forward values and gradients). The program fails if they diverge,
// so the generated documents and animation data are guaranteed to match the code.
//
// Outputs:
//
//	docs/numeric/data/<layer>.json  machine readable fixture for manim animations
//	docs/numeric/<layer>.md         human readable step-by-step walkthrough
import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strings"
)

const (
	numericDir = "docs/numeric"
	dataDir    = "docs/numeric/data"
)

func main() {
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		panic(err)
	}
	if err := generateLinear(); err != nil {
		fmt.Println("linear:", err)
		os.Exit(1)
	}
	if err := generateConv2D(); err != nil {
		fmt.Println("conv2d:", err)
		os.Exit(1)
	}
	if err := generateSolvers(); err != nil {
		fmt.Println("solvers:", err)
		os.Exit(1)
	}
	fmt.Println("all fixtures generated and verified")
}

// writeJSON dumps fixture payload for animations
func writeJSON(name string, payload interface{}) error {
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dataDir, name+".json"), append(data, '\n'), 0644)
}

func writeMarkdown(name, content string) error {
	header := "<!-- Generated by cmd/docsgen. Do not edit manually: run go run ./cmd/docsgen instead -->\n\n"
	return os.WriteFile(filepath.Join(numericDir, name+".md"), []byte(header+content), 0644)
}

// fmtNum prints a float as an integer when possible, keeping the walkthroughs readable
func fmtNum(v float64) string {
	if v == math.Trunc(v) {
		return fmt.Sprintf("%d", int64(v))
	}
	return fmt.Sprintf("%.4g", v)
}

// texMatrix renders a 2D matrix for MathJax/KaTeX.
// The array environment with an explicit column list is used instead of pmatrix:
// amsmath matrices of MathJax are limited to 10 columns by default and wide inputs
// of the examples exceed that, while the *{n}{c} repetition shorthand is not supported by KaTeX
func texMatrix(m [][]float64) string {
	out := fmt.Sprintf("\\left(\\begin{array}{%s}", strings.Repeat("c", len(m[0])))
	for i, row := range m {
		for j, v := range row {
			if j > 0 {
				out += " & "
			}
			out += fmtNum(v)
		}
		if i < len(m)-1 {
			out += " \\\\ "
		}
	}
	return out + "\\end{array}\\right)"
}

// almostEqual guards manual computations against the library implementation
func almostEqual(a, b float64) bool {
	return math.Abs(a-b) <= 1e-9
}
